package views;

import controllers.Controlador;
import helpers.EstiloFilas;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author yh9pl
 */
public class JDProyecto extends javax.swing.JDialog {

    /**
     * Creates new form JDProyecto
     */
    public JDProyecto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Aplicar estilo de filas tipo Excel a la tabla
        this.jtDatosBinarios.setDefaultRenderer(Object.class, new EstiloFilas());
        JTableHeader header = this.jtContingencia.getTableHeader();
        header.setDefaultRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                           boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel(value.toString());
                label.setOpaque(true);
                label.setBackground(new Color(0xCCCCFF));
                label.setForeground(new Color(0xCCCCFF));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setBorder(UIManager.getBorder("TableHeader.cellBorder"));
                return label;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        txtItems = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtInstancias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiarItems = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlItems = new javax.swing.JList<>();
        txtNombreItem = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCrearTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDatosBinarios = new javax.swing.JTable();
        btnExcel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbItem1 = new javax.swing.JComboBox<>();
        cmbItem2 = new javax.swing.JComboBox<>();
        lblSeleccion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtContingencia = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setFocusable(false);
        background.setLayout(null);

        txtItems.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItems.setForeground(new java.awt.Color(153, 153, 153));
        txtItems.setText("0");
        txtItems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemsKeyTyped(evt);
            }
        });
        background.add(txtItems);
        txtItems.setBounds(20, 70, 70, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Items");
        background.add(jLabel1);
        jLabel1.setBounds(20, 40, 80, 20);

        txtInstancias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInstancias.setForeground(new java.awt.Color(153, 153, 153));
        txtInstancias.setText("0");
        txtInstancias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInstanciasKeyTyped(evt);
            }
        });
        background.add(txtInstancias);
        txtInstancias.setBounds(100, 70, 70, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("TABLA DE CONTINGENCIA");
        background.add(jLabel2);
        jLabel2.setBounds(560, 40, 180, 20);

        btnLimpiarItems.setText("Limpiar Datos");
        background.add(btnLimpiarItems);
        btnLimpiarItems.setBounds(20, 240, 150, 30);

        jlItems.setFocusable(false);
        jScrollPane1.setViewportView(jlItems);

        background.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 150, 70);

        txtNombreItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreItem.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreItem.setText("Nombre Item");
        txtNombreItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreItemKeyPressed(evt);
            }
        });
        background.add(txtNombreItem);
        txtNombreItem.setBounds(20, 120, 110, 30);

        btnAgregar.setText("+");
        background.add(btnAgregar);
        btnAgregar.setBounds(140, 120, 30, 30);

        btnCrearTabla.setBackground(new java.awt.Color(102, 102, 255));
        btnCrearTabla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearTabla.setText("Crear tabla binaria");
        btnCrearTabla.setEnabled(false);
        background.add(btnCrearTabla);
        btnCrearTabla.setBounds(20, 280, 150, 30);

        jtDatosBinarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtDatosBinarios.setFocusable(false);
        jtDatosBinarios.setShowVerticalLines(true);
        jtDatosBinarios.getTableHeader().setResizingAllowed(false);
        jtDatosBinarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtDatosBinarios);

        background.add(jScrollPane2);
        jScrollPane2.setBounds(180, 70, 360, 240);

        btnExcel.setBackground(new java.awt.Color(33, 163, 102));
        btnExcel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcel.setForeground(new java.awt.Color(255, 255, 255));
        btnExcel.setText("Cargar tabla Excel");
        background.add(btnExcel);
        btnExcel.setBounds(20, 320, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Instancias");
        background.add(jLabel3);
        jLabel3.setBounds(100, 40, 80, 20);

        cmbItem1.setEnabled(false);
        background.add(cmbItem1);
        cmbItem1.setBounds(330, 320, 100, 30);

        cmbItem2.setEnabled(false);
        background.add(cmbItem2);
        cmbItem2.setBounds(440, 320, 100, 30);

        lblSeleccion.setText("Seleccionar Items:");
        lblSeleccion.setEnabled(false);
        background.add(lblSeleccion);
        lblSeleccion.setBounds(220, 325, 100, 16);

        jtContingencia.setBackground(new java.awt.Color(204, 204, 255));
        jtContingencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtContingencia.setFocusable(false);
        jtContingencia.setGridColor(new java.awt.Color(255, 255, 255));
        jtContingencia.setRowSelectionAllowed(false);
        jtContingencia.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jtContingencia.setShowHorizontalLines(true);
        jtContingencia.setShowVerticalLines(true);
        jtContingencia.getTableHeader().setResizingAllowed(false);
        jtContingencia.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtContingencia);

        background.add(jScrollPane3);
        jScrollPane3.setBounds(560, 70, 240, 110);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("TABLA BINARIA");
        background.add(jLabel4);
        jLabel4.setBounds(180, 40, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void txtItemsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemsKeyTyped
        char c = evt.getKeyChar();
        if (!(c >= '2' && c <= '8')) {
            evt.consume(); // Consume el evento para evitar que se procese
        }
        // Verifica que el campo tenga solo un carácter
        if (this.txtItems.getText().length() >= 1) {
            evt.consume(); // Consume el evento si ya hay un carácter
        }
    }//GEN-LAST:event_txtItemsKeyTyped

    private void txtInstanciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstanciasKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
        if(this.txtInstancias.getText().indexOf('0') == 0) {
            evt.consume();
        }
    }//GEN-LAST:event_txtInstanciasKeyTyped

    private void txtNombreItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreItemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if((this.txtItems.getText().equals("0") || this.txtItems.getText().equals("")) ||
               (this.txtInstancias.getText().equals("0") || this.txtInstancias.getText().equals(""))) {
                JOptionPane.showMessageDialog(this, "Debes ingresar valores validos de items e instancias.", "Reglas de Asociación", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(this.txtNombreItem.getText().equals("") || this.txtNombreItem.getText().equals("Nombre Item")) {
                JOptionPane.showMessageDialog(this, "Debes ingresar un nombre de item.", "Reglas de Asociación", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(this.jlItems.getModel().getSize() < Integer.parseInt(this.txtItems.getText())) {
                Controlador.listModel.addElement(this.txtNombreItem.getText());
                this.jlItems.setModel(Controlador.listModel);
                this.txtNombreItem.setText("");
                this.txtNombreItem.requestFocus();
                if(this.jlItems.getModel().getSize() == Integer.parseInt(this.txtItems.getText())) {
                    this.btnCrearTabla.setEnabled(true);
                    this.btnCrearTabla.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aumenta el número de items para agregar más.", "Reglas de Asociación", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_txtNombreItemKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDProyecto dialog = new JDProyecto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel background;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCrearTabla;
    public javax.swing.JButton btnExcel;
    public javax.swing.JButton btnLimpiarItems;
    public javax.swing.JComboBox<String> cmbItem1;
    public javax.swing.JComboBox<String> cmbItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> jlItems;
    public javax.swing.JTable jtContingencia;
    public javax.swing.JTable jtDatosBinarios;
    public javax.swing.JLabel lblSeleccion;
    public javax.swing.JTextField txtInstancias;
    public javax.swing.JTextField txtItems;
    public javax.swing.JTextField txtNombreItem;
    // End of variables declaration//GEN-END:variables
}
